export const ROUTE_PATHS = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    EMAIL_CODE: '/email-code',
    EMAIL_SEND: '/email-sent',
    RESET_PASSWORD: '/reset-password',
    CONFIRM_PASSWORD: '/confirm-password',
    CREATE_PROPERTY: '/create-property',
    SEARCH: '/search',
    NOT_FOUND: '/*',
    PARTNERS: '/partners',
    PARTNERS_ADMINISTRATION: '/partners-administration',
    PROPERTY_MANAGEMENT: '/property-management',
    PARTNER_INTEGRATION_REQUEST: '/partner-integration-request',
    PROPERTY_DETAILS: '/property-details/:propertyId',
    APPOINTMENTS: '/appointments',
    REQUEST_APPOINTMENTS: '/request-appointments',
    USER_PROFILE: '/user-profile',
    GENERAL_INFORMATION: '/user-profile/general-information',
    GENERAL_INFORMATION_PARTNER: '/user-profile/general-information-partner',
    PREFERENCES: '/user-profile/preferences',
    PARTNER_SERVICES: '/user-profile/partner-services',
    OPERATIONAL_HOURS: '/user-profile/operational-hours',
    CHANGE_PASSWORD: '/user-profile/change-password',
    EDIT_PROPERTY: '/edit-property/:id',
    FAVORITES: '/favorites',
    PARTNER_PROFILE: '/partner-profile/:partnerId',
    SEARCH_PARTNERS: '/search-partners',

};
